/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2022-09-05 06:25:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class parameterDesc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>04/parameterDesc.jsp</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h4>요청 파라미터 처리</h4>\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/formDataProcess\" method=\"post\">\r\n");
      out.write("<pre>\r\n");
      out.write("\t<input type=\"text\" name=\"paramIpt1\" placeholder=\"paramIpt1\"/>\r\n");
      out.write("\t<input type=\"number\" name=\"paramIpt2\" placeholder=\"paramIpt2\"/>\r\n");
      out.write("\t<input type=\"date\" name=\"paramIpt3\" placeholder=\"paramIpt3\"/>\r\n");
      out.write("\t<input type=\"radio\" name=\"paramIpt4\" id=\"paramIpt4_R1\" placeholder=\"paramIpt4\" value=\"R1\"/>\r\n");
      out.write("\t<label for=\"paramIpt4_R1\">\r\n");
      out.write("\tR1\r\n");
      out.write("\t</label>\r\n");
      out.write("\t<input type=\"radio\" name=\"paramIpt4\" id=\"paramIpt4_R2\" placeholder=\"paramIpt4\" value=\"R2\"/>\r\n");
      out.write("\t<label for=\"paramIpt4_R2\">\r\n");
      out.write("\tR2\r\n");
      out.write("\t</label>\r\n");
      out.write("\t<label><input type=\"checkbox\" name=\"paramIpt5\" value=\"CHECK1\">CHECK1</label>\r\n");
      out.write("\t<label><input type=\"checkbox\" name=\"paramIpt5\" value=\"CHECK2\">CHECK2</label>\r\n");
      out.write("\t<label><input type=\"checkbox\" name=\"paramIpt5\" value=\"CHECK3\">CHECK3</label>\r\n");
      out.write("\t<select name=\"paramIpt6\" required>\r\n");
      out.write("\t\t<option value>선택</option>\r\n");
      out.write("\t\t<option value=\"옵션1\">OPT1</option>\r\n");
      out.write("\t\t<option value=\"옵션2\">OPT2</option>\r\n");
      out.write("\t\t<option value=\"옵션3\">OPT3</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<select name=\"paramIpt7\" multiple>\r\n");
      out.write("\t\t<option value=\"옵션1\">OPT1</option>\r\n");
      out.write("\t\t<option value=\"옵션2\">OPT2</option>\r\n");
      out.write("\t\t<option value=\"옵션3\">OPT3</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<textarea rows=\"\" cols=\"\" name=\"paramIpt8\" placeholder=\"paramIpt8\"></textarea>\r\n");
      out.write("\t<input type=\"submit\" value=\"전송\">\r\n");
      out.write("</pre>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
